"""Minimal Stage2 generic-candidate model and solver utilities."""

from .io import load_distance_lookup, load_stage2_input
from .models import (
    DistanceLookup,
    FixedLambdaSelection,
    FixedLambdaTileSelection,
    LambdaBracketResult,
    LambdaSearchConfig,
    LambdaSearchResult,
    LambdaSelectedCandidate,
    LambdaTracePoint,
    LookupDistanceMatch,
    LookupPdlSupport,
    LookupResolution,
    LookupRule,
    Stage2Input,
    Stage2LocalUpgradeAudit,
    Stage2LocalUpgradeStep,
    Stage2Message,
    Stage2SelectedTile,
    Stage2SolveResult,
    Tile,
    TransmissionCandidate,
)
from .preprocess import (
    bracket_lambda_for_feasible_candidate,
    compute_b_min_feasible,
    compute_net_utility,
    compute_spatial_utility,
    is_better_feasible_candidate,
    match_lookup_rule,
    resolve_allowed_candidates,
    resolve_lookup_for_input,
    search_lambda_feasible_candidates,
    select_fixed_lambda,
)
from .solver import solve_stage2

__all__ = [
    "DistanceLookup",
    "FixedLambdaSelection",
    "FixedLambdaTileSelection",
    "LambdaBracketResult",
    "LambdaSearchConfig",
    "LambdaSearchResult",
    "LambdaSelectedCandidate",
    "LambdaTracePoint",
    "LookupDistanceMatch",
    "LookupPdlSupport",
    "LookupResolution",
    "LookupRule",
    "Stage2Input",
    "Stage2LocalUpgradeAudit",
    "Stage2LocalUpgradeStep",
    "Stage2Message",
    "Stage2SelectedTile",
    "Stage2SolveResult",
    "Tile",
    "TransmissionCandidate",
    "bracket_lambda_for_feasible_candidate",
    "compute_b_min_feasible",
    "compute_net_utility",
    "compute_spatial_utility",
    "is_better_feasible_candidate",
    "load_distance_lookup",
    "load_stage2_input",
    "match_lookup_rule",
    "resolve_allowed_candidates",
    "resolve_lookup_for_input",
    "search_lambda_feasible_candidates",
    "select_fixed_lambda",
    "solve_stage2",
]
